### ISSUE TITLE
Adding Barrel Search Functionality in the reverse Index

### ISSUE THREAD

**Issue by EggsyOnCode** [EggsyOnCode/search-engine-news#6]
# Task
add barrel search functioanlity into reverse index; and make sure both "search from barrel" and "search from reverse_index" options are avaialble; (add the choice as param to the constructor)

this means if search from barrel is enabled 
we would not deseralize the reversed_index.json file instead we would load all the barrel files into an array like self.barrels=[] in the constructor; 
and whenever we are searching in the reverse_index for a word ; we would first would the barrel_id in which to search using this func

def find_barrel_for_word_id(self, word_id):
        return word_id % len(self.barrels)

and then we'll search in the respective barrel using this

self.barrels[barrel_id][wordID]

and if search from reverse_index.json is chosen then we just do the normal stuff; we deseralize from index json instead of barrel

inorder to do this ; you'd have to make separate func (desearialzie from json and deserailzie from barrel) and conditionally process

# Reason
n my barrel implementation; i am reading the reverse_index.json and dividing it into a few parts; but obv in this way barrels are  being loaded into RAM as python dict instead of the DS that our reversed index has (a hashmap; pointing to a list of nodes)

this means if i load these barrels as it is, they wouldn't perform we intend them to

**Comment by EggsyOnCode** [comment]
Merge to barrels branch ; NOT MAIN

**Comment by Ignavar** [comment]
made pull request into barrels branch
